build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: eCalendar"
  org.opencontainers.image.description: "Daily planner - events, chores, lists, weather"
  org.opencontainers.image.source: "https://github.com/matt-gun/ecalendar-ha"
